import '../scss/style.scss'
import brands from '../blocks/brands/brands.js'
import technic from '../blocks/technic/technic.js'
import modal from '../blocks/modal/modal.js'
import menu from '../blocks/menu/menu.js'
import swiper from '../blocks/swiper/swiper.js'
